# Generated by Django 4.1.1 on 2022-09-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queandans',
            old_name='q_ans_c',
            new_name='q_ans_closed',
        ),
        migrations.RenameField(
            model_name='queandans',
            old_name='q_ans_o_long',
            new_name='q_ans_open_long',
        ),
        migrations.RenameField(
            model_name='queandans',
            old_name='q_ans_o_small',
            new_name='q_ans_open_small',
        ),
    ]
