# Generated by Django 4.1.1 on 2022-09-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0003_formsample_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
