# Generated by Django 4.1.1 on 2022-09-24 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0004_remove_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9)),
                ('half', models.CharField(max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='teacher_a',
            new_name='teacher_assistant',
        ),
        migrations.RemoveField(
            model_name='form',
            name='desciption',
        ),
        migrations.AddField(
            model_name='formsample',
            name='desciption',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='formsample',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='assessment_app.queandans'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_of_course', to='assessment_app.coursename'),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_of_course', to='assessment_app.term'),
        ),
    ]
