# Generated by Django 4.1.1 on 2022-09-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0006_alter_formsample_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queandans',
            options={'verbose_name': 'Question & Answer', 'verbose_name_plural': 'Questions & Answers'},
        ),
    ]
