# Generated by Django 4.1.1 on 2022-09-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0008_images_teacher_photo_teacherassistant_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Image file', 'verbose_name_plural': 'Image files'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='idnumber',
        ),
    ]
