# Generated by Django 4.1.1 on 2022-09-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0009_alter_images_options_remove_student_idnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(max_length=150)),
                ('taken', models.BooleanField()),
            ],
        ),
    ]
