# Generated by Django 4.1.1 on 2022-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0010_idnumbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idnumbers',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
