# Generated by Django 4.1.1 on 2022-09-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0011_alter_idnumbers_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Question & Answer',
                'verbose_name_plural': 'Questions & Answers',
            },
        ),
        migrations.DeleteModel(
            name='QueAndAns',
        ),
        migrations.AlterModelOptions(
            name='idnumbers',
            options={'verbose_name': 'ID Number', 'verbose_name_plural': 'ID Numbers'},
        ),
        migrations.AlterField(
            model_name='formsample',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='questions', to='assessment_app.questions'),
        ),
    ]
