# Generated by Django 4.1.1 on 2022-09-26 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0013_coursename_number_coursename_type_formsample_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnswerS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_open', models.CharField(blank=True, max_length=3000, null=True)),
                ('answer_closed', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='which_course', to='assessment_app.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='which_question', to='assessment_app.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans_student', to='assessment_app.student')),
            ],
            options={
                'verbose_name': 'Form answer (student)',
                'verbose_name_plural': 'Form answers (students)',
            },
        ),
    ]
