# Generated by Django 4.1.1 on 2022-09-26 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0015_questiontype_alter_questions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_type', to='assessment_app.questiontype'),
        ),
    ]
