# Generated by Django 4.1.1 on 2022-09-26 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0016_alter_questions_q_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Subject (Form)', 'verbose_name_plural': 'Subjects (Forms)'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Subject (Form)', 'verbose_name_plural': 'Subjects (Forms)'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher_assistant',
        ),
        migrations.AddField(
            model_name='teacher',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeacherAssistant',
        ),
    ]
