# Generated by Django 4.1.1 on 2022-09-26 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0018_alter_teacher_supervisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher/TA', 'verbose_name_plural': 'Teachers/TAs'},
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=3000)),
                ('score_needed', models.PositiveIntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
