# Generated by Django 4.1.1 on 2022-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0019_alter_teacher_options_student_score_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='teacher',
            name='supervisor',
            field=models.ManyToManyField(blank=True, related_name='supervisor_of_TA', to='assessment_app.teacher'),
        ),
    ]
