# Generated by Django 4.1.1 on 2022-09-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0021_alter_coursename_number_alter_coursename_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursename',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
