# Generated by Django 4.1.1 on 2022-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0022_alter_coursename_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursename',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursename',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
