# Generated by Django 4.1.1 on 2022-09-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0024_remove_coursename_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursename',
            name='number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursename',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
