# Generated by Django 4.1.1 on 2022-09-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0027_alter_course_options_alter_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='form',
            new_name='form_sample',
        ),
    ]
