# Generated by Django 4.1.1 on 2022-09-28 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0031_course_is_teacher_assisstant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_of_ta', to='assessment_app.teacher'),
        ),
    ]
