# Generated by Django 4.1.1 on 2022-09-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0032_course_current_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formanswers',
            old_name='course',
            new_name='form',
        ),
    ]
