# Generated by Django 4.1.1 on 2022-09-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0033_rename_course_formanswers_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['q_type'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='course',
            name='student_not_answered',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students_not_answered', to='assessment_app.student'),
        ),
    ]
