# Generated by Django 4.1.1 on 2022-09-30 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0034_alter_questions_options_course_student_not_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=3000)),
                ('score_needed', models.PositiveIntegerField()),
                ('student', models.ManyToManyField(blank=True, related_name='able_to_enroll', to='assessment_app.student')),
            ],
            options={
                'verbose_name': 'Prize',
                'verbose_name_plural': 'Prizes',
            },
        ),
        migrations.CreateModel(
            name='PrizesGot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_name', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='assessment_app.student')),
            ],
            options={
                'verbose_name': 'Prize log',
                'verbose_name_plural': 'List of gotten prizes',
            },
        ),
        migrations.DeleteModel(
            name='Prize',
        ),
    ]
