# Generated by Django 4.1.1 on 2022-09-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0036_course_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsample',
            old_name='desciption',
            new_name='description',
        ),
    ]
