# Generated by Django 4.1.1 on 2022-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0037_rename_desciption_formsample_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizename',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
