# Generated by Django 4.1.1 on 2022-10-01 04:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0039_alter_prizesgot_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='prizesgot',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
